### ISSUE TITLE
Better Icon

### ISSUE THREAD

**Issue by TheodoreHua** [TheodoreHua/AlreadyClaimedNotifier#1]
Exactly what the title says. Attach a better icon here (via image link) and I'll update it on the application. Recommended dimensions are 128x128 and file format as PNG.

**Comment by chakeson** [comment]
Hello, I made an icon [link](https://drive.google.com/file/d/1BPOnjqwGbkSWLSzCbVxrNPqZ_VfEcC3r/view?usp=sharing)
Web browser may render the transparent parts white but there is a 64px radius white circle in the center so it's a round icon.

**Comment by TheodoreHua** [comment]
Thanks, that'll work perfectly!
